### ISSUE TITLE
install error since enabled debug files

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/secadm#23]
kldxref /boot/kernel
===> libsecadm (install)
install -s -o root -g wheel -m 444     libsecadm.so.0 /usr/lib/
install -T debug -o root -g wheel -m 444    libsecadm.so.0.debug /usr/lib/debug/usr/lib/
install: /usr/lib/debug/usr/lib/: No such file or directory
*** Error code 71

Stop.
make[1]: stopped in /secadm/libsecadm
*** Error code 1

Stop.
make: stopped in /secadm
root@internal:/secadm # mkdir -p /usr/lib/debug/usr/lib/
root@internal:/secadm # make install
===> etc (install)
===> etc/rc.d (install)
install -o root  -g wheel -m 555  secadm  /usr/local/etc/rc.d//secadm
===> kmod (install)
install -o root -g wheel -m 555   secadm.ko /boot/kernel/
kldxref /boot/kernel
===> libsecadm (install)
install -s -o root -g wheel -m 444     libsecadm.so.0 /usr/lib/
install -T debug -o root -g wheel -m 444    libsecadm.so.0.debug /usr/lib/debug/usr/lib/
install -l s libsecadm.so.0 /usr/lib/libsecadm.so
install -C -o root -g wheel -m 444  /secadm/libsecadm/secadm.h /usr/include/
===> secadm (install)
install -s -o root -g wheel -m 555   secadm /usr/sbin/secadm
install -T debug -o root -g wheel -m 444  secadm.debug /usr/lib/debug/usr/sbin/secadm.debug
install: /usr/lib/debug/usr/sbin/secadm.debug: No such file or directory
*** Error code 71

Stop.
make[1]: stopped in /secadm/secadm
*** Error code 1

**Comment by lattera** [comment]
Below is an IRC conversation I had with Bryan Drewery:

> 21:28 < lattera> bdrewery: ping
21:28 < lattera> regarding WITH_DEBUG_FILES
21:28 < lattera> (I know, that's Ed Maste's thing, but you know bsd make much better than I)
Day changed to 19 Feb 2016
10:41 -!- mode/#bsdcode [+l 133] by lor
13:47 <@bdrewery> lattera: what's up?
13:48 < lattera> bdrewery: so I have an application (secadm) that lives outside of base, but uses bsd.*.mk to do its thing
13:49 < lattera> in the `make install` phase, if /usr/lib/debug doesn't exist, `make install` still tries to install .debug files, but fails
13:49 < lattera> https://github.com/HardenedBSD/secadm/issues/23 <- here's the issue
13:50 < lattera> I tried manually setting MK_DEBUG_FILES="no", but bsd.mkopt.mk throws an error when I do that
13:50 < lattera> what's the proper way to say "please don't install debug files with ${DESTDIR}/lib/debug doesn't exist?"
13:50 <@bjk> MK_* are for internal use; use WITHOUT_ instead.
13:51 <@bdrewery> lattera: why no /usr/lib/debug/usr/lib?
13:51 < cem> Just create /usr/lib/debug :)
13:51 < cem> YEah
13:51 <@bdrewery> it should be there by default
13:51 <@bdrewery> and why no secadm.debug?
13:52 < lattera> bdrewery: because this user decided not to install debug files
13:52 <@bdrewery> so why is it trying to install them?
13:52 < lattera> it's a brand new install, and bsdinstall allows the user to decide whether or not to install the debug distset
13:52 < lattera> because the user has no src.conf
13:52 < cem> the root distset should include the directories
13:52 <@bdrewery> did they manually rm -rf /usr/lib/debug ?
13:52 < cem> and bsdinstall should write out a no-debug-files src.conf if the user deselects debug
13:53 < lattera> cem: base.txz does not contain /usr/lib/debug
13:53 < lattera> http://jenkins.hardenedbsd.org/builds/HardenedBSD-CURRENT-amd64-LATEST/
13:53 < cem> Right -- IMO that's a bug
13:53 < lattera> you'll see there's a base-dbg.txz and a kernel-dbg.txz
13:53 < lattera> bdrewery: no, they didn't rm -rf /usr/lib/debug... it didn't exist in the first place
13:53 <@bdrewery> oh, you have this build outside of the src tree
13:54 < lattera> right
13:55 < lattera> so here's the wrench I'm throwing in: if ${DESTDIR}/lib/debug does exist, I do want to install the .debug files...
13:56 < lattera> is DESTDIR defined by a bsd.*.mk include?
13:56 < lattera> ${DESTDIR}/usr/lib/debug, rather
13:57 <@bdrewery> putting any of that logic in your files is the wrong place
13:57 <@bdrewery> let me think about it and see what I can do in bsd.lib.mk
13:58 < lattera> okay
13:58 < lattera> thanks :)

**Comment by lattera** [comment]
@bdrewery is working on this from FreeBSD's side: https://reviews.freebsd.org/D5411

I'm closing this bug report since FreeBSD will fix it.
